- slug: playford_1651
  title: The English Dancing Master (1651)
  dates:
  - 1651
- slug: caroso_nobilita_di_dame
  title: Nobilità di Dame (1600)
  dates:
  - 1600
- slug: caroso_il_ballarino
  title: Il Ballarino (1581)
  dates:
  - 1581
